<?php


namespace App\Modules\Restaurant\Repositories;


use App\Modules\BaseRepository;
use App\Modules\Restaurant\Models\HolidayHour;

class HolidayHourRepository extends BaseRepository
{
    public function __construct(HolidayHour $holidayHour)
    {
        parent::__construct($holidayHour);
    }


    public function addHour(array $data){

        $begin = new DateTime($data['start_date']);
        $end = new DateTime($data['end_date']);

        $interval = DateInterval::createFromDateString('1 day');
        $period = new DatePeriod($begin, $interval, $end);

        foreach ($period as $dt) {
            $this->model->updateOrCreate(array(
                'date' => $dt->format("Y-m-d")
            ));
        }

        return 'Holiday hours added successfully.';    }


    public function listHours(){
        return $this->model->orderBy('date', 'asc')->get();
    }

    public function delete(string $id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }

}
